2020-01-14 17:42:53,048 ERROR: Exception on /favicon.ico [GET] [in c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\flask\app.py", line 1925, in dispatch_request
    self.raise_routing_exception(req)
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\flask\app.py", line 1907, in raise_routing_exception
    raise request.routing_exception
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\flask\ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\werkzeug\routing.py", line 1799, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\flask\app.py", line 1815, in handle_user_exception
    return self.handle_http_exception(e)
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\flask\app.py", line 1743, in handle_http_exception
    return handler(e)
  File "C:\Users\vuno\srv\learing.python\python\mypy\microblog\app\errors\handlers.py", line 7, in not_found_error
    return render_template('errors/404.html'), 400
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\vuno\srv\learing.python\python\mypy\microblog\app\templates\base.html", line 40, in template
    {% end if %}
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\vuno\srv\learing.python\python\mypy\microblog\app\templates\errors\404.html", line 11, in root
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\jinja2\loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\jinja2\environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\vuno\srv\learing.python\python\mypy\microblog\app\templates\base.html", line 40, in template
    {% end if %}
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\jinja2\parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\jinja2\parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\jinja2\parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\jinja2\parser.py", line 212, in parse_if
    node.body = self.parse_statements(('name:elif', 'name:else',
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\jinja2\parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\jinja2\parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\jinja2\parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\jinja2\parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "c:\users\vuno\srv\learing.python\python\mypy\microblog\envflask\lib\site-packages\jinja2\parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'end'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
